### PR TITLE
PHP 8.0 Support

### PR DESCRIPTION
**Pull request by octoper**
This PR adds PHP 8.0 support for Expose

It looks like the following also need to be updated to support PHP 8.

- ~~https://github.com/laravel-zero/framework/pull/421~~
- ~~https://github.com/laminas/laminas-http/pull/45~~
- ~~https://github.com/laminas/laminas-validator/pull/75~~

### CODE REVIEW

**Comment by mpociot** [comment]
@octoper Thanks for the PR, what is still missing before we can merge this?

**Comment by octoper** [comment]
@mpociot We are waiting for Laravel Zero (https://github.com/laravel-zero/framework/pull/421)  and Laminas HTTP (https://github.com/laminas/laminas-http/pull/45) to add support for PHP 8, then we can merge!

**Comment by owenvoke** [comment]
Just a heads up, Laravel Zero v8.4.0 has now been released with support for PHP 8. 👍🏻

**Comment by SamuelNitsche** [comment]
Laminas HTTP v2.14.0 has also been released which supports PHP 8.

**Comment by octoper** [comment]
I will try to have it ready by tomorrow morning..

**Comment by octoper** [comment]
Looks like we have to wait a bit more for this one https://github.com/laminas/laminas-validator/pull/75  to get merged so the lhttps://github.com/laminas/laminas-http has **real** PHP 8 Support

**Comment by lahivee** [comment]
these PRs need more love

**Comment by octoper** [comment]
@lahivee You can spnosor me from my GitHub's sponsor page but I think the main person you need to sponsor is @mpociot

**Comment by octoper** [comment]
cc @mpociot This PR is ready for review!

**Comment by mpociot** [comment]
awesome, thank you very much. I will look into this later today - and I'll also need to backport this to the 1.x branch, as `master` is already for the upcoming 2.x version.

**Comment by Iamscaredofcode** [comment]
Thank you for the work and efforts!! @octoper @mpociot

**Comment by lahivee** [comment]
yes thank you!! please merge this before the weekend and post your Bitcoin address and i will send you some BTC @mpociot

**Pull request merged**
