### PR TITLE
Add support for windows home path (fixes #14)

### LINKED ISSUE #14: Expose throws error on Windows when running the 'expose token' command
I tried to set my authentication token on windows by running 
`expose token sUpEr-AwEsOmE-fAkE-tOkEn`

but it throws an error 

`In StoreAuthenticationTokenCommand.php line 27: `
  `Undefined index: HOME`

ff

bug maybe?

### PR DESCRIPTION
**Pull request by innocenzi**
`HOME` is a valid environment variable un *nix systems, but not in Windows, where `USERPROFILE` is used. For this reason, there was an issue when trying to access the user profile directory, to access configuration for instance. 

This PR fixes this issue simply by replacing `$_SERVER['HOME']` by `$_SERVER['HOME'] ?? $_SERVER['USERPROFILE']`. It should fix #14. 

By the way, certainly unrelated, but most tests fail on Windows, [they timeout](https://i.imgur.com/sNNyRok.png), so I can't assert that I didn't insert breaking changes with this PR.

### CODE REVIEW

**Comment by mpociot** [comment]
thank you!

**Comment by E360Franco** [comment]
EXCELLENT FIX AND INPUT/expose/pull/
CONTRIBUTE//87..*UT

**Comment by abhiburk** [comment]
I have installed the expose globally but these changes arent there in my package ? I am facing same issue `Undefined index: HOME`

**Comment by E360Franco** [comment]
I DID NOT LEAVE SAID MESSAGE ABOVE..  APPEARS MY LOGIN HERE IS COMPRIMISED.  SHUT DOWN.

**Pull request merged**
